version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: portfolio-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: portfolio
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: portfolio-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data: